DATA:
  data_name: s3dis
  data_root: datasets/S3DIS/blocks_bs1_s1/data # Fill in the pre-processed data path (which contains the .npy files)
  classes: 13
  fea_dim: 6
  voxel_size: 0.02
  voxel_max: 20480
  loop: 1
  cvfold: 0

TRAIN:
  #arch
  arch: stratified_transformer
  stem_transformer: True
  use_xyz: True
  sync_bn: False  # adopt sync_bn or not
  rel_query: True
  rel_key: True
  rel_value: True
  quant_size: 0.01
  downsample_scale: 8
  num_layers: 4 
  patch_size: 1 
  window_size: 4
  depths: [2, 2, 6, 2] 
  channels: [48, 96, 192, 384] 
  num_heads: [3, 6, 12, 24] 
  up_k: 3
  drop_path_rate: 0.3
  concat_xyz: True
  grid_size: 0.04
  max_batch_points: 140000
  max_num_neighbors: 34 # For KPConv
  ratio: 0.25
  k: 16

  # training
  aug: True
  transformer_lr_scale: 0.1
  jitter_sigma: 0.005
  jitter_clip: 0.02
  scheduler_update: epoch 
  scheduler: MultiStep 
  warmup: linear
  warmup_iters: 1500
  warmup_ratio: 0.000001
  use_amp: True
  optimizer: AdamW 
  ignore_label: 255
  train_gpu: [0, 1, 2, 3]  # Fill in the gpu ids for training, e.g., [0, 1, 2, 3]
  workers: 16  # data loader workers
  base_lr: 0.00005
  epochs: 100
  start_epoch: 0
  step_epoch: 30
  multiplier: 0.1
  momentum: 0.9
  weight_decay: 0.01
  drop_rate: 0.5
  manual_seed: 123
  # manual_seed:
  print_freq: 10
  save_freq: 1
  save_path: ./my_weights/s3dis # Fill the path to store the trained model
  weight:  # path to initial weight (default: none)
  resume:  # path to latest checkpoint (default: none)
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  eval_freq: 1
  eval_start_epoch: 3        # 从第几轮开始验证


Few-shot:
  num_episode: 400             # 训练episode数量
  n_way: 1                     # 每个episode的类别数（N-way）
  k_shot: 1                    # 每类支持集样本数（K-shot）
  n_queries: 1                 # 每个episode的查询样本数
  num_episode_per_comb: 1000   # 每种类别组合的episode数量
  pretrain_backbone:           # 预训练主干路径
  n_subprototypes: 200         # 每类原型数
  vis: 0                       # 可视化相关参数
  forvis: 0                    # 可视化相关参数
  vis_save_path:               # 可视化结果保存路径
  target_class: table          # 目标类别
  num_inference_samples: 3     # 推理时采样次数
  base_proto_ema: 0.999        # 基础类别原型EMA系数
  var_infer_hidden_dim: 96     # 变分推理MLP隐藏层维度
  max_kl_weight: 1.0           # KL loss最大权重
  fixed_num_points: 2048       # 每个样本固定点数
  kl_warmup_epochs: 10         # KL损失warmup轮数
  kl_warmup_type: linear       # KL损失warmup类型 (linear/cosine/exponential)
  pa_type: dpr                # 原型注意力模式：dpr(双流)/spr(单流)
  use_vpir: 1                   # 是否启用VPIR（1启用，0关闭）


Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0

TEST:
  test: False
  eval_split: test # split for eval in [val or test], should be set to 'test' if test is True
